services:
  - type: web
    name: frontend
    env: docker
    buildCommand: npm install && npm run build
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_BACKEND_URL
        value: https://backend.onrender.com

  - type: web
    name: backend
    env: docker
    buildCommand: npm install
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI} # Aqui, apenas referencie a variável de ambiente
